from decouple import config


APP_HOST = config('APP_HOST')
APP_PORT = config('APP_PORT', cast=int)
POSTGRES_HOST = config('POSTGRES_HOST')
POSTGRES_PORT = config('POSTGRES_PORT', cast=int)
POSTGRES_USER = config('POSTGRES_USER')
POSTGRES_PASSWORD = config('POSTGRES_PASSWORD')
POSTGRES_DB = config('POSTGRES_DB')

DB_URL = f'postgresql+asyncpg://{POSTGRES_HOST}/{POSTGRES_DB}?user={POSTGRES_USER}&password={POSTGRES_PASSWORD}'
DB_POOL_SIZE = 10
DB_CONNECTION_TIMEOUT_S = 60
